stock_list = [
    {'Ticker': 'AAPL',
     'Buy_Date': '20210219',
     'Buy_Price': 129.39,
     'Quantity': 100,
     'Buy_Currency': 'USD',
     'Brokerfee': 9.99,
     'Sell_Date': '',
    },
    {'Ticker': 'AC.TO',
     'Buy_Date': '20220307',
     'Buy_Price': 20.25,
     'Quantity': 300,
     'Buy_Currency': 'CAD',
     'Brokerfee': 9.99,
     'Sell_Date': '',
    },
    {'Ticker': 'CAE',
     'Buy_Date': '20220316',
     'Buy_Price': 24,
     'Quantity': 200,
     'Buy_Currency': 'USD',
     'Brokerfee': 9.99,
     'Sell_Date': '',
    },
    {'Ticker': 'CHPT',
     'Buy_Date': '20220217',
     'Buy_Price': 11,
     'Quantity': 300,
     'Buy_Currency': 'USD',
     'Brokerfee': 9.99,
     'Sell_Date': '',
    },
    {'Ticker': 'F',
     'Buy_Date': '20220307',
     'Buy_Price': 16,
     'Quantity': 300,
     'Buy_Currency': 'USD',
     'Brokerfee': 9.99,
     'Sell_Date': '',
    },
    {'Ticker': 'GLW',
     'Buy_Date': '20220330',
     'Buy_Price': 30.029,
     'Quantity': 300,
     'Buy_Currency': 'USD',
     'Brokerfee': 9.99,
     'Sell_Date': '',
    },
    {'Ticker': 'JETS',
     'Buy_Date': '20220321',
     'Buy_Price': 20.13,
     'Quantity': 300,
     'Buy_Currency': 'USD',
     'Brokerfee': 9.99,
     'Sell_Date': '',
    },
    {'Ticker': 'NYCB',
     'Buy_Date': '20220207',
     'Buy_Price': 11.42,
     'Quantity': 300,
     'Buy_Currency': 'USD',
     'Brokerfee': 9.99,
     'Sell_Date': '',
    },
    {'Ticker': 'SNC.TO',
     'Buy_Date': '20211129',
     'Buy_Price': 31.95,
     'Quantity': 100,
     'Buy_Currency': 'CAD',
     'Brokerfee': 9.99,
     'Sell_Date': '',
    },
    {'Ticker': 'VALE',
     'Buy_Date': '20211018',
     'Buy_Price': 14.30,
     'Quantity': 300,
     'Buy_Currency': 'USD',
     'Brokerfee': 9.99,
     'Sell_Date': '',
    },
    {'Ticker': 'T',
     'Buy_Date': '20220412',
     'Buy_Price': 19.60,
     'Quantity': 300,
     'Buy_Currency': 'USD',
     'Brokerfee': 9.99,
     'Sell_Date': '',
    },
]


